# Generated by Django 3.1.2 on 2020-10-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='campana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='nombre')),
                ('organizacion', models.CharField(blank=True, max_length=100, verbose_name='organizacion')),
                ('fecha', models.DateField()),
                ('ubicacion', models.CharField(blank=True, max_length=100, verbose_name='ubicacion')),
                ('celular', models.IntegerField(blank=True, verbose_name='celular')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('correo', models.CharField(blank=True, max_length=100, verbose_name='correo')),
            ],
            options={
                'verbose_name': 'campana',
                'verbose_name_plural': 'campanas',
            },
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='nombre')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('celular', models.IntegerField(blank=True, verbose_name='celular')),
                ('ubicacion', models.CharField(blank=True, max_length=100, verbose_name='ubicacion')),
                ('correo', models.CharField(blank=True, max_length=100, verbose_name='correo')),
            ],
            options={
                'verbose_name': 'hospital',
                'verbose_name_plural': 'hospitales',
            },
        ),
        migrations.CreateModel(
            name='incentivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='nombre')),
                ('empresa', models.CharField(blank=True, max_length=100, verbose_name='empresa')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(blank=True, max_length=100, verbose_name='tipo')),
                ('celular', models.IntegerField(blank=True, verbose_name='celular')),
                ('correo', models.CharField(blank=True, max_length=100, verbose_name='correo')),
            ],
            options={
                'verbose_name': 'incentivo',
                'verbose_name_plural': 'incentivos',
            },
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, verbose_name='apellido')),
                ('documento', models.CharField(blank=True, max_length=100, verbose_name='documento')),
                ('numDocumento', models.IntegerField(blank=True, verbose_name='numDocumento')),
                ('grupo', models.CharField(blank=True, max_length=100, verbose_name='grupo')),
                ('rh', models.CharField(blank=True, max_length=100, verbose_name='rh')),
                ('fecha', models.DateField()),
                ('genero', models.CharField(blank=True, max_length=100, verbose_name='genero')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('celular', models.IntegerField(blank=True, verbose_name='celular')),
                ('correo', models.CharField(blank=True, max_length=100, verbose_name='correo')),
                ('contrasena', models.CharField(blank=True, max_length=100, verbose_name='contrasena')),
                ('confirmar', models.CharField(blank=True, max_length=100, verbose_name='confirmar')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
