# Generated by Django 3.1.3 on 2020-11-26 00:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datos_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(blank=True, max_length=100, verbose_name='documento')),
                ('numDocumento', models.IntegerField(blank=True, verbose_name='numDocumento')),
                ('grupo', models.CharField(blank=True, max_length=100, verbose_name='grupo')),
                ('rh', models.CharField(blank=True, max_length=100, verbose_name='rh')),
                ('fecha', models.DateField()),
                ('genero', models.CharField(blank=True, max_length=100, verbose_name='genero')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('celular', models.IntegerField(blank=True, verbose_name='celular')),
                ('username', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'datos_usuario',
                'verbose_name_plural': 'datos_usuarios',
            },
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
